In [1]:
import numpy as np   # For data handling.
import pandas as pd  #  # For data handling.
from sklearn.model_selection import train_test_split  # Split data into train and test.
from sklearn.preprocessing import MinMaxScaler  # Normalize the data between 0 and 1.
from tensorflow.keras.models import Sequential  # Used to build the Neural Network using Keras.
from tensorflow.keras.layers import Dense  # Used to build the Neural Network using Keras.
import matplotlib.pyplot as plt # To visualize the training process (loss over epochs).

In [2]:
# Sample Data (Hours Studied vs Exam Score)
data = {
    'Hours': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Score': [15, 25, 35, 45, 55, 65, 70, 78, 88, 95]
}
df = pd.DataFrame(data)

In [3]:
df.shape

(10, 2)

In [4]:
df

,Hours,Score
0,1,15
1,2,25
2,3,35
3,4,45
4,5,55
5,6,65
6,7,70
7,8,78
8,9,88
9,10,95


In [5]:
X = df[['Hours']] # InDepended variable (Input)
y = df['Score'] # Depended variable (output)
y.head()

0    15
1    25
2    35
3    45
4    55
Name: Score, dtype: int64

In [6]:
# Normalize Features
# Neural networks work better if data is between 0 and 1.
# MinMaxScaler converts Hours into 0–1 range.
# Prevents big numbers from dominating small numbers during training.
# For Example orignal hours 1 --> 0.0  , 10 --> 1.0
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.        ],
       [0.11111111],
       [0.22222222],
       [0.33333333],
       [0.44444444],
       [0.55555556],
       [0.66666667],
       [0.77777778],
       [0.88888889],
       [1.        ]])

In [7]:
# Split Data
# 80% data for training, 20% data for testing.
# random_state=42 ensures reproducibility.
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
X_test

array([[0.88888889],
       [0.11111111]])

In [8]:
X_train

array([[0.55555556],
       [0.        ],
       [0.77777778],
       [0.22222222],
       [1.        ],
       [0.44444444],
       [0.33333333],
       [0.66666667]])

In [9]:
#  Build ANN Model
model = Sequential()

# Hidden layer:
# 10 neurons, ReLU activation
# input_shape=(1,) → 1 input feature (Hours)
model.add(Dense(10, activation='relu', input_shape=(1,)))

# Output layer:
# 1 neuron for predicted score
model.add(Dense(1))

C:\Users\HP\3D Objects\Desktop\DA_using_Python\ML\tfenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [11]:
# Compile model
# Adam → optimizer
# MSE → loss function for regression
model.compile(
    optimizer='adam',
    loss='mean_squared_error')

In [12]:
# Train model
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2, # 20% training data for validation
    epochs=100,           # Train 100 times
    verbose=0             # Hide training logs
)
#The model adjusts weights over epochs to minimize loss.

In [14]:
# Predict score for 8 hours of study
# Since data is normalized:
# 8 hours ≈ 0.8 

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Predicted Score for 8 hours of study: 0.27
